name: Feature CICD Development

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Test
        run: echo "Running on the feature branch"

      - name: Deploy
        run: echo "Deploying onto the feature branch"
